application: psvgdurandal
version: 1
runtime: python27
threadsafe: true
api_version: 1

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest



handlers:

- url: /favicon(\.png)|(\.ico)
  static_files: client/resources/favicon.png
  upload: client/resources/favicon\.ico

- url: /client
  static_dir: client

- url: /.*
  script: server.controller.app